### ISSUE TITLE
Why is absolute value used in model matrix

### ISSUE THREAD

**Issue by rguliev** [khliland/EMSC#2]
In [line 189](https://github.com/khliland/EMSC/blob/7857921c75686db87eabd8638e53d2e2f762e33b/R/EMSC.R#L189) an absolute value is taken, but I did not found any explanation for that. Could you, please, explain it?

**Comment by khliland** [comment]
Dear Rustam,

When using QR decomposition to produce orthogonal polynomials, the sign of the offset (constant ones) is sometimes flipped. Though this has little to say in practice, it is customary to have a positive offset as default.

Best regards,
Kristian
