### ISSUE TITLE
What are constituent?

### ISSUE THREAD

**Issue by rguliev** [khliland/EMSC#3]
By looking at the code I could not understand what are constituents. From the code it looks like they are used exactly the same as interferents. For example, [here](https://github.com/khliland/EMSC/blob/7857921c75686db87eabd8638e53d2e2f762e33b/R/EMSC.R#L103) they are excluded.
Another question is what is the difference between constituent and reference?

**Comment by khliland** [comment]
Dear Rustam,

The original formulation of reference, constituents and interferents was that the reference spectrum was the basic spectrum that the other spectra were adjusted towards (scaling and baseline), while constituents were spectra of measured compounds and interferents were spectra of unwanted signals. The latter are corrected for, together with the baseline, while the constituents are only used to stabilize the model, not for corrections. However, the exact effect of the various spectra is dependent on the data being analysed and how these are combined.

Regards,
Kristian

**Comment by rguliev** [comment]
> The latter are corrected for, together with the baseline, while the constituents are only used to stabilize the model, not for corrections. 

But in the code there is no difference between interferents  and constituents. That what confused me. For example, in [this](https://github.com/khliland/EMSC/blob/7857921c75686db87eabd8638e53d2e2f762e33b/R/EMSC.R#L103) line, constituents are also removed.

Another question is, Is there any difference between a) multiple reference spectra and b) one reference spectra and constituents? It looks to me that, when multiply reference spectra is supported, then constituents parameter can be removed from the function.

**Comment by khliland** [comment]
Dear Rustam,

The constituents are not removed at the line you refer to. If you look at the index, only `k:terms` is removed, where `terms` is defined [here](https://github.com/khliland/EMSC/blob/7857921c75686db87eabd8638e53d2e2f762e33b/R/EMSC.R#L73). Constituents are positioned after the reference, polynomials, interferents and, possibly, replicate correction spectra, thus not included in the correction.

The key difference between references spectra and constituents is that the multiplicative part of EMSC, i.e. the scaling, is with respect to references, not the constituents.

Best regards,
Kristian

**Comment by rguliev** [comment]
Ok. Now, I got it:)
Thank you!
