### ISSUE TITLE
QR decomposition

### ISSUE THREAD

**Issue by rguliev** [khliland/EMSC#4]
I was a little bit confused with QR decomposition in the code:

1. First, QR decomposition is done only for polynomial components [(here)](https://github.com/khliland/EMSC/blob/7857921c75686db87eabd8638e53d2e2f762e33b/R/EMSC.R#L188). However, the original paper that is provided in resources suggest to do that for the whole model matrix
2. Then `mldivide` is used for solving the LS problem. And `mldivide` uses QR decomposition for that. Does it look like the QR decomposition is applied twice? Is there a reason for that?

**Comment by khliland** [comment]
Dear Rustam,

1. The first QR decomposition is used for orthogonalizing the baseline polynomials to make sure that these contribute independently in modelling and correction.
2. The [`mldivide`](https://github.com/cran/pracma/blob/master/R/mldivide.R) function uses `qr.solve(A, B)`, i.e. solves the linear system with A and B. This is the same as in the `lm` function of base R, but without all the added computations and logic.

Best regards,
Kristian
